In [2]:
import numpy as np
import pandas as pd

PART1

In [3]:
cht = pd.read_csv('california_housing_train.csv')

In [4]:
cht

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]

In [8]:
cht.head(5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [9]:
cht.tail(10)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16990    -124.22     41.73                28.0       3003.0           699.0   
16991    -124.23     41.75                11.0       3159.0           616.0   
16992    -124.23     40.81                52.0       1112.0           209.0   
16993    -124.23     40.54                52.0       2694.0           453.0   
16994    -124.25     40.28                32.0       1430.0           419.0   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
16990      1530.0       653.0         1.7038             78300.0  
16991      1343.0       479.0         2.4805             73200.0  
16992       544.0       172.0         3.3462             50800.0  
16993      1152.0       435.0         3.0806            106700.0  
16994       434.0       187.0         1.9417             76100.0  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0

In [10]:
cht.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [12]:
unique_values = cht['total_bedrooms'].unique()
print(unique_values)


[1283. 1901.  174. ... 1637. 1308.  936.]


In [13]:
cht['total_bedrooms'].nunique()

1848

In [14]:
cht['total_bedrooms_per_total_rooms'] = cht['total_bedrooms']/cht['total_rooms']
cht

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  \
0          1015.0       472.0         1.4936             66900.0   
1          1129.0       463.0         1.8200             80100.0   
2           333.0       117.0         1.6509             85700.0   
3           515.0       226.0         3.1917             73400.0   
4           624.0       262.0         1.9250             65500.0   
...           ...         ...            ...                 ...   
16995       907.0       369.0         2.3571            111400.0   
16996      1194.0       465.0         2.5179             79000.0   
16997      1244.0       456.0         3.0313            103600.0   
16998      1298.0       478.0         1.9797             85800.0   
16999       806.0       270.0         3.0147             94600.0   

       total_bedrooms_per_total_rooms  
0                            0.228617  
1                            0.248497  
2                            0.241667  
3                            0.224517  
4                            0.224209  
...                               ...  
16995                        0.177718  
16996                        0.224777  
16997                        0.198356  
16998                        0.206587  
16999                        0.164835  

[17000 rows x 10 columns]

In [15]:
cht['total_bedrooms_per_total_rooms'].describe()

count    17000.000000
mean         0.212760
std          0.057823
min          0.100000
25%          0.175058
50%          0.202943
75%          0.239867
max          1.000000
Name: total_bedrooms_per_total_rooms, dtype: float64

so mean = 0.212760, standard deviation = 0.057823

In [17]:
cht.loc[(cht['median_income']>5)]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
32       -115.39     32.76                16.0       1136.0           196.0   
69       -115.55     32.98                33.0       2266.0           365.0   
92       -115.57     32.78                20.0       1534.0           235.0   
98       -115.58     32.78                 5.0       2494.0           414.0   
100      -115.59     32.79                 8.0       2183.0           307.0   
...          ...       ...                 ...          ...             ...   
16737    -122.89     38.38                16.0       2017.0           369.0   
16762    -122.94     38.57                33.0       1530.0           266.0   
16776    -123.00     38.33                 8.0       3223.0           637.0   
16802    -123.17     39.18                14.0       2240.0           327.0   
16899    -124.05     40.94                14.0       1452.0           217.0   

       population  households  median_income  median_house_value  \
32          481.0       185.0         6.2558            146300.0   
69          952.0       360.0         5.4349            143000.0   
92          871.0       222.0         6.2715             97200.0   
98         1416.0       421.0         5.7843            110100.0   
100        1000.0       287.0         6.3814            159900.0   
...           ...         ...            ...                 ...   
16737       931.0       336.0         5.7664            267500.0   
16762       728.0       250.0         5.1005            266700.0   
16776       851.0       418.0         5.6445            364800.0   
16802      1030.0       308.0         5.9585            214900.0   
16899       516.0       181.0         5.0329            165600.0   

       total_bedrooms_per_total_rooms  
32                           0.172535  
69                           0.161077  
92                           0.153194  
98                           0.165998  
100                          0.140632  
...                               ...  
16737                        0.182945  
16762                        0.173856  
16776                        0.197642  
16802                        0.145982  
16899                        0.149449  

[3752 rows x 10 columns]

In [18]:
cht.loc[(cht['total_rooms']>10000) & (cht['median_house_value']<150000)]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
133      -116.06     34.15                15.0      10377.0          2331.0   
191      -116.36     33.88                11.0      12557.0          3098.0   
198      -116.38     33.73                10.0      11836.0          2405.0   
201      -116.39     33.82                15.0      11115.0          2257.0   
229      -116.47     33.81                 7.0      10105.0          2481.0   
...          ...       ...                 ...          ...             ...   
12654    -121.75     38.67                 9.0      12139.0          2640.0   
12772    -121.79     36.64                11.0      32627.0          6445.0   
13388    -121.94     38.27                35.0      10869.0          2226.0   
13707    -122.00     38.25                 7.0      11768.0          1893.0   
15436    -122.31     40.55                11.0      13714.0          2302.0   

       population  households  median_income  median_house_value  \
133        4507.0      1807.0         2.2466             66800.0   
191        2453.0      1232.0         1.7844             78500.0   
198        3811.0      1570.0         4.0079            134500.0   
201        4122.0      1653.0         2.7219             74400.0   
229        6274.0      2095.0         2.4497             90900.0   
...           ...         ...            ...                 ...   
12654      6837.0      2358.0         3.1250            132500.0   
12772     28566.0      6082.0         2.3087            118800.0   
13388      9879.0      2152.0         2.5681             81300.0   
13707      6657.0      1874.0         4.9222            142900.0   
15436      6511.0      2267.0         3.5522            100100.0   

       total_bedrooms_per_total_rooms  
133                          0.224631  
191                          0.246715  
198                          0.203194  
201                          0.203059  
229                          0.245522  
...                               ...  
12654                        0.217481  
12772                        0.197536  
13388                        0.204803  
13707                        0.160860  
15436                        0.167858  

[67 rows x 10 columns]

In [20]:
cht.to_csv('new_california_housing_train.csv')

PART 2

In [24]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
even_nums = arr[arr%2 == 0]
even_nums

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [25]:
new_arr = np.random.randint(10,100,size = (5,4))
new_arr

array([[52, 12, 50, 48],
       [53, 67, 61, 58],
       [42, 99, 57, 44],
       [15, 82, 94, 69],
       [34, 45, 29, 98]])

In [27]:
new_arr[:3,:2]

array([[52, 12],
       [53, 67],
       [42, 99]])

In [33]:
arr = arr.reshape((4,5))
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [35]:
arr = arr.reshape((1,20))
print(arr)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]]


In [44]:
random_arr = np.random.randint(100, size = (4,5))
np.matmul(random_arr,new_arr)

array([[ 8351, 12588, 12312, 12761],
       [10540, 13309, 13833, 12866],
       [ 4104,  5274,  4776,  9294],
       [ 6847, 14248, 13560, 15760]])

In [46]:
arr_new = np.random.randint(100,size = 50)
arr_new

array([65, 48,  8, 60, 38, 33, 24,  3, 20, 69, 19, 39, 64, 80, 57, 55, 18,
       21, 90, 63,  9, 94,  8, 36, 66, 44, 16, 82, 15, 60, 68, 73, 31, 65,
       74, 18,  0, 71, 17, 65, 79, 57,  8, 11, 99, 26, 72,  4, 10, 34])

In [47]:
arr_new[arr_new>50]

array([65, 60, 69, 64, 80, 57, 55, 90, 63, 94, 66, 82, 60, 68, 73, 65, 74,
       71, 65, 79, 57, 99, 72])

In [48]:
arr_new[[1,3,7,28]]

array([48, 60,  3, 15])

In [50]:
mean_col = np.mean(new_arr,axis = 0)
max_col = np.max(new_arr, axis = 0)
min_col = np.min(new_arr, axis = 0)
print(mean_col)
print(max_col)
print(min_col)

[39.2 61.  58.2 63.4]
[53 99 94 98]
[15 12 29 44]


In [52]:
mask = new_arr>mean_col
filtered_arr = new_arr[mask]
print(filtered_arr)

[52 53 67 61 42 99 82 94 69 98]


PART 3

In [55]:
a = 0
b = 1
while(a<100):
    print(a)
    a,b = b,a+b

0
1
1
2
3
5
8
13
21
34
55
89


In [63]:
for i in range(1,51):
    if i%3 == 0:
        if i%5 == 0:
            print("FizzBuzz")
        else:
            print("Fizz")
    elif i%3 != 0:
        if i%5 == 0:
            print("Buzz")
        else :
            print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz


In [70]:

numbers = list(map(int, input("Enter numbers separated by spaces: ").split()))

print("List of numbers:", numbers)


def find_median(numbers):
    sorted_numbers = sorted(numbers)
    n = len(sorted_numbers)

    if n%2 == 1:
        return sorted_numbers[n//2]
    else:
        mid1,mid2 = sorted_numbers[n//2 -1],sorted_numbers[n//2]
        return(mid1+mid2)/2

print("The median of given numbers is: ", find_median(numbers))

Enter numbers separated by spaces:  1 5 91 73 43


List of numbers: [1, 5, 91, 73, 43]
The median of given numbers is:  43


In [71]:
values = list(map(int, input("Enter numbers separated by spaces: ").split()))
n = len(values)
sum_values = 0
for i in range(n):
    sum_values += values[i]

avg = sum_values/n
print("Avg of the given numbers is: ",avg)

Enter numbers separated by spaces:  7 91 23 65 1


Avg of the given numbers is:  37.4


In [72]:
a = int(input("Enter numerator: "))
b = int(input("Enter denominator: "))

if b==0 :
    print("Division by zero is undefined")
else:
    print(a/b)

Enter numerator:  4
Enter denominator:  0


Division by zero is undefined
